config/routes.rb
Rails.application.routes.draw do
  get 'collections/datacite_search', to: 'collections#datacite_search'
  post 'collections/crossref_search', to: 'collections#crossref_search'
  get "collections/import_metadata", to: 'collections#import_metadata', as: 'import_collection'
  get 'collections/ldap_search', to: 'collections#ldap_search'
  get 'dashboard/publishables', to: 'publishables#index', as: 'dashboard_publishables'
  get 'help', to: 'contact_form#new', as: 'help_page'
  get 'policies', to: 'pages#show', id: 'policies_page', as: 'policies'
  get 'user_guides', to: 'pages#show', id: 'user_guides_page', as: 'user_guides'
  get 'collections/:id/add-files', to: 'collections#add_files', as: 'collections_add_files'
  get 'collections/:id/dataset-download(/:admin)', to: 'collections#dataset_download', as: 'collections_download'
  get 'dashboard/admin_metadata_download', to: 'dashboard#admin_metadata_download', as: 'admin_metadata_download'
  
  get 'users/depositors', to: 'users#depositor_list_export', as: 'depositor_list'

  blacklight_for :catalog

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'users/auth/cas', to: 'users/omniauth_callbacks#passthru', as: 'new_user_session'
  devise_scope :user do
    get 'sign_in', to: redirect('/users/auth/cas')
    get 'sign_out', to: 'devise/sessions#destroy', as: 'destroy_user_session'
  end

  mount Orcid::Engine => "/orcid"

  mount Hydra::RoleManagement::Engine => '/'

  resources :doi_requests, :only => [:index, :create] do
    member do
      patch 'mint_doi'
      get 'view_doi'
    end

    collection do
      get 'pending'
      patch 'mint_all'
    end
  end

  Hydra::BatchEdit.add_routes(self)

  mount Sufia::Engine => '/'
  root to: 'homepage#index'

end

app/models/collection.rb
class Collection < Sufia::Collection

  property :funder, predicate: ::RDF::DC.provenance do |index|
    index.as :stored_searchable, :facetable
  end

end

app/models/sufia/collection.rb
module Sufia
  class Collection < ActiveFedora::Base
    include Sufia::CollectionBehavior

    before_destroy :delete_doi_requests

    def delete_doi_requests
      requests = DoiRequest.where(asset_id: self.id)
      if !requests.empty?
        requests.each do |request|
          request.destroy
        end
      end
    end

    def csv_headers
      ['id', 'title', 'creator', 'contributor', 'abstract', 'keyword', 'rights', 'publisher', 'date_created', 'subject', 'language', 'identifier', 'location', 'related_url', 'funding_info', 'items']
    end

    def admin_csv_headers
      admin_solr_headers.concat admin_fedora_headers
    end

    def admin_solr_headers
      ["system_create_dtsi", "system_modified_dtsi", "active_fedora_model_ssi", "has_model_ssim", "object_profile_ssm", "depositor_ssim", "depositor_tesim", "title_tesim", "description_tesim", "publisher_tesim", "publisher_sim", "resource_type_tesim", "resource_type_sim", "identifier_tesim", "hasCollectionMember_ssim", "read_access_group_ssim", "edit_access_person_ssim"]
    end

    def admin_fedora_headers
      ["id", "depositor", "part_of", "contributor", "creator", "title", "description", "publisher", "date_created", "date_uploaded", "date_modified", "subject", "language", "rights", "resource_type", "identifier", "based_near", "tag", "related_url", "funder", "member_ids"]
    end

    def admin_csv_values
      ret_array = []
      admin_solr_headers.each do | key |
        value = !self.to_solr[key].blank? ? self.to_solr[key] : ""
        ret_array << (value.respond_to?("each") ? value.join("||") : value)
      end
      admin_fedora_headers.each do | key |
        value = !self.send(key).blank? ? self.send(key) : ""
        ret_array << (value.respond_to?("each") ? value.join("||") : value)
      end
      ret_array
    end

    def csv_values
      ret_array = []
      ret_array << self.id
      ret_array << self.title
      ret_array << self.creator.join('||')
      ret_array << self.contributor.join('||')
      ret_array << self.description
      ret_array << self.tag.join('||')
      ret_array << self.rights.join('||')
      ret_array << self.publisher.join('||')
      ret_array << self.date_created.join('||')
      ret_array << self.subject.join('||')
      ret_array << self.language.join('||')
      ret_array << self.identifier.join('||')
      ret_array << self.based_near.join('||')
      ret_array << self.related_url.join('||')
      ret_array << self.funder.join('||')
      ret_array << self.member_ids.join('||')
    end

  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include Hydra::Catalog
  include Sufia::CollectionsControllerBehavior
  require 'vtech_data/download_generator'

  skip_load_and_authorize_resource :only => [:datacite_search, :crossref_search, :import_metadata, :ldap_search, :add_files, :dataset_download]

  def presenter_class
    MyCollectionPresenter
  end

  def form_class
    MyCollectionEditForm
  end

  def show
    super
    max_dataset_for_export = 3 * 1024 * 1024 * 1024
    @dataset_size = 0
    @can_export = true
    if @collection.members.respond_to?('each')
      @collection.members.each do |generic_file|
        if generic_file.file_size.blank?
          @can_export = false
          break
        end
        file_size = generic_file.file_size.first.to_i
        @dataset_size += file_size
      end
    end
    @can_export = (@can_export && @dataset_size <= max_dataset_for_export)
  end

  def after_create
      respond_to do |format|
        ActiveFedora::SolrService.instance.conn.commit
        format.html { redirect_to collections.collection_path(@collection), notice: 'Dataset was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      end
  end

  def create
    @collection.apply_depositor_metadata(current_user.user_key)
    add_members_to_collection unless batch.empty?

    if !params[:collection][:funder].nil? && !params[:collection][:funder].empty?
      params[:collection][:funder].each do |funder|
        if funder.length > 0
          values = funder.split(":")
          @collection[:funder] << "<funder><fundername>#{values[0]}</fundername><awardnumber>#{values[1]}</awardnumber></funder>"
        end
      end
    end

    if params[:request_doi]
      @collection[:identifier] << t('doi.pending_doi')
    end

    if @collection.save
      if params[:request_doi]
        doi_request = DoiRequest.new(asset_id: @collection.id)
        if doi_request.save
          flash[:notice] = t('doi.messages.submit.success')
        else
          flash[:error] = t('doi.messages.submit.failure')
        end
      end

      after_create
    else
      after_create_error
    end
  end

  def update
    process_member_changes
    if @collection.update(collection_params.except(:members))
      newfunder = []
      if !params[:collection][:funder].nil? && !params[:collection][:funder].empty?
        params[:collection][:funder].each do |funder|
          if funder.length > 0
            values = funder.split(":")
            newfunder << "<funder><fundername>#{values[0]}</fundername><awardnumber>#{values[1]}</awardnumber></funder>"
          end
        end
      end
      @collection.update_attributes({:funder => newfunder})
      @collection[:identifier].each do |id|
        # Matches DOIs minted by VT Libraries
        if /\A#{Ezid::Client.config.default_shoulder}/ =~ id
          ezid_doi = Ezid::Identifier.find(id)
          if ezid_doi
            ezid_doi.update_metadata(
              datacite_creator: (@collection.creator.empty? ? "" : @collection.creator.first),
              datacite_title: @collection.title,
              datacite_publisher: (@collection.publisher.empty? ? "" : @collection.publisher.first),
              datacite_publicationyear: (@collection.date_created.empty? ? "" : @collection.date_created.first)
            )
          end
          if ezid_doi.save
            flash[:notice] = t('doi.messages.modify.success')
          else
            flash[:error] = t('doi.messages.modify.failure')
          end
          break
        end
      end
      after_update
    else
      after_update_error
    end
  end

  def datacite_search
    uri = URI('http://search.datacite.org/api?')
    uri.query = URI.encode_www_form(params)
    res = Net::HTTP.get(uri)
    parsed = JSON.parse(res)
    if parsed["responseHeader"]["status"] != 0
      @datacite_error = "Datacite server problem. You can fill in on your own."
      render :action => 'datacite_search_error'
    elsif parsed["response"]["numFound"] == 0
      @datacite_error = "No metadata found! You can fill in on your own."
      render :action => 'datacite_search_error'
    else
      @results = parsed["response"]["docs"]
    end
  end

  def crossref_search
    @results = JSON.parse(params[:results])
  end

  def import_metadata
    @result = params[:result].gsub('=>', ':')
  end

  def ldap_search
    ldap = Net::LDAP.new(host: 'directory.vt.edu')
    ldap.bind
    treebase = 'ou=People,dc=vt,dc=edu'
    ldap_attributes = {uid: :authid, display_name: :displayname, department: :department, address: :postaladdress}
    name = params[:name].gsub(/\s/,'*')
    filter = Net::LDAP::Filter.eq("cn", "*#{name}*")
    @results = ldap.search(base: treebase, filter: filter)
    @radio_name = params[:label]
    render :layout => false
  end

  def add_files
    if current_user.admin?
      self.search_params_logic += [:show_only_generic_files, :add_access_controls_to_solr_params]
    else
      self.search_params_logic += [:show_only_generic_files, :show_only_resources_deposited_by_current_user]
    end
    (@response, @files) = search_results({ q: '', rows: 10000 }, search_params_logic)
    @collection = Collection.find(params[:id])
    authorize! :edit, @collection
  end

  def dataset_download
    time_stamp = DateTime.now.strftime('%Q')
    download_generator = DownloadGenerator.new(time_stamp)
    download_generator.make_archive
    admin_download = (!params[:admin].blank? && params[:admin] == "admin")
    download_generator.generate_dataset_download(params[:id], admin_download)
    zip_file = download_generator.zip
    while !File.file? zip_file
      sleep(0.1)
    end
    send_file zip_file
  end
end

app/helpers/collection_helper.rb
module CollectionHelper
  def deletable_dataset(id)
    collection = Collection.find(id)
    collection[:identifier].each do |id|
      if /\A#{Ezid::Client.config.default_shoulder}/ =~ id
        return false
      end
    end
    return true 
  end
end

app/views/collections/_crossref_search.html.erb
<%= text_field_tag :query %>
<%= hidden_field_tag :rows, "20" %>
<%= hidden_field_tag :offset, "0" %>
  
<input type="button" value="Search CrossRef" id="crossref_button" />

app/views/collections/_crossref_search_result.html.erb
<% if @results.nil? || @results.empty? %>
  <h2>No metadata found!</h2>
<% else %>
  <div class="table-responsive" id="related_url_form">
    <table class="table table-striped table-hover">
      <caption><%= pluralize(@results.size, 'Record') %> found</caption>
      <thead>
      <tr>
        <th>&nbsp;</th>
        <th>DOI</th>
        <th>Title</th>
        <th>Authors</th>
        <th>Year</th>
      </tr>
      </thead>
      <tbody>
      <% @results.each_with_index do |result, idx| %>
        <tr>
          <% if idx == 0 %>
            <td><%= radio_button_tag 'result', result["DOI"], true %></td>
          <% else %>
            <td><%= radio_button_tag 'result', result["DOI"] %></td>
          <% end %>
          <td><%= result["DOI"] %></td>
          <td><%= result["title"].first %> </td>
          <td><%= result["author"] %> </td>
          <td><%= result["deposited"]["date-parts"].first.first %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/collections/_datacite_search.html.erb
<%= form_tag('datacite_search', method: :get, remote: true) do %>
  <%= label_tag(:q, "Datacite Metadata Search: ") %>
  <%= text_field_tag :q %>
  <%= hidden_field_tag :fl, "doi, creator, publisher, publicationYear, title" %>
  <%= hidden_field_tag :rows, "20" %>
  <%= hidden_field_tag :wt, "json" %>
  <%= submit_tag("Search") %>
<% end %>
<br/>
Or <button id="direct_fill_form">Directly Fill Form</button>

app/views/collections/_datacite_search_result.html.erb
<% if @results.nil? || @results.empty? %>
  <h2><%= @datacite_error %></h2>
<% else %>
  <%= form_tag('import_metadata', method: :get, remote: true) do %>
    <div class="table-responsive">
    <table class="table table-striped table-hover">
      <caption>Choose one from below:</caption>
      <thead>
      <tr>
        <th>&nbsp;</th>
        <th>DOI</th>
        <th>Creator</th>
        <th>Publisher</th>
        <th>Publication Year</th>
        <th>Title</th>
      </tr>
      </thead>
      <tbody>

      <% @results.each_with_index do |result, idx| %>
        <tr>
          <% if idx == 0 %>
            <td><%= radio_button_tag 'result', result, true %></td>
          <% else %>
            <td><%= radio_button_tag 'result', result %></td>
          <% end %>
          <td><%= result["doi"] %></td>
          <td><%= result["creator"] %> </td>
          <td><%= result["publisher"] %></td>
          <td><%= result["publicationYear"] %></td>
          <td><%= result["title"] %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= submit_tag("Import Metadata") %>
  <% end %>
<% end %>

app/views/collections/_form.html.erb
<%= simple_form_for [collections, @form], html: {class: 'form-horizontal editor'} do |f| %>
  <div id="descriptions_display">
    <h2 class="non lower">Descriptions</h2>
    <span class="error pull-right"><small>*</small> indicates required fields</span> 
    <div class="well">
      <% f.object.terms.each do |term| %>
        <%= render_edit_field_partial term, f: f %>
      <% end %>
    </div><!-- /well -->
  </div>
  <%= hidden_field_tag :type, params[:type] %>
  <% if params[:batch_document_ids].present? %>
    <% params[:batch_document_ids].each do |batch_item| %>
      <input type="hidden" name="batch_document_ids[]" value="<%= batch_item %>"/>
    <% end %>
  <% end %>

  <div class="primary-actions">
    <% if params[:action] == "new" %>
      <%= f.submit 'Create Dataset', class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "create_submit", name: "create_collection" %>
    <% else %>
      <%= f.submit 'Update Dataset', class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "update_submit", name: "update_collection" %>
    <% end %>
    <%= link_to t(:'helpers.action.cancel'), main_app.root_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/collections/_form_for_select_collection.html.erb
<div role="dialog" class="modal fade" id="collection-list-container" tabindex="-1" aria-labelledby="col_add_title" >
  <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><%= t('sufia.collection.select_form.close_button') %></button>
          <span class="modal-title" id="col_add_title"><%= t("sufia.collection.select_form.title") %></span>
        </div>
        <div class="modal-body">
          <% if user_collections.blank? %>
            <em> <%= t("sufia.collection.select_form.no_collections") %></em><br><br><br><br>
          <% else %>
            <div class="collection-list">
              <fieldset>
                <legend><%= t("sufia.collection.select_form.select_heading") %></legend>
              <ul>
                <% user_collections.sort { |c1,c2| c2[CatalogController.uploaded_field] <=> c1[CatalogController.uploaded_field] }.each_with_index do |collection,index|  %>
                  <li>
                    <% selected = (collection.id == @add_files_to_collection) || (@add_files_to_collection.blank? && index == 0) %>
                    <%= radio_button_tag(:id, collection.id, selected, class: "collection-selector") %>
                    <%= label_tag(:collection, collection.title, for: "id_#{collection.id}") %>
                  </li>
                <% end %>
              </ul>
              </fieldset>
            </div><!-- collection-list -->
          <% end %> <!-- else -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t("sufia.collection.select_form.close")%></button>
          <% if user_collections.blank? %>
            <%= button_for_create_collection t("sufia.collection.select_form.create") %>
          <% else %>
            <%= button_for_update_collection t("sufia.collection.select_form.update") %>
            <%= button_for_create_collection t("sufia.collection.select_form.create_new") %>
          <% end %>
        </div>
      </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/collections/_search_form.html.erb
<div style="float: right;" >
  <%= form_for [collections, @collection], method: :get, class: "well form-search" do |f| %>

      <label class="accessible-hidden">Search Dataset <%= @collection.title.first %></label>
      <%= text_field_tag :cq, params[:cq], class: "collection-query", placeholder: "Search Dataset", size: '30', type: "search", id: "collection_search" %>
      <%= hidden_field_tag :sort, params[:sort], id: 'collection_sort' %>
      <%= render_hash_as_hidden_fields(params_for_search.except(:cq, :sort, :qt, :page)) %>
      <button type="submit" class="btn btn-primary" id="collection_submit"><i class="icon-search"></i> Go</button>
  <% end %>
</div>

app/views/collections/_show_actions.html.erb
<h2 class="sr-only">Actions</h2>
<div class="collection-controls">
    <% if can? :edit, @collection %>
      <div class="btn-group collection-control-row" role="group" aria-label="...">
        <%= link_to collections.edit_collection_path, class: "btn btn-default", title: "Edit this Dataset" do %>
          <span class="glyphicon glyphicon-edit"></span> Edit
        <% end %>
        <%= link_to  collections_add_files_path(@collection), class: "btn btn-default", title: "Edit this Dataset" do %>
          <span class="glyphicon glyphicon-file"></span> Files
        <% end %>
        <div>The maximum export dataset file size is limited to 3GB.</div>
        <% if @can_export %>
          <%= link_to collections_download_path(@collection), class: "btn btn-default", title: "Export this Dataset" do %>
            <span class="glyphicon glyphicon-download"></span> Export dataset
          <% end %>
        <% else %>
          <div style="clear:both">The size of this dataset is too large to export or is unknown.</div>
        <% end %>
      </div>
    <% end %>
</div>

app/views/collections/add_files.html.erb
<%= render partial: 'dashboard/_index_partials/heading_actions.html.erb' %>
<h1><%= t('datarepo.gf_metaname').capitalize %>s in <%= @collection.title %></h1>
<% if @files.empty? %>
  <span>Please upload some <%= t('datarepo.gf_metaname') %>s first.</span>
<% else %>
  <%= form_for @collection, url: collections.collection_path(@collection) do |f| %>
  <%= hidden_field_tag "collection[members][]" %>
  <div class="table-responsive">
    <table class="table table-actionable table-striped table-hover">
      <thead>
        <tr>
          <th class="text-left"><%= t('datarepo.gf_metaname') %></th>
          <th>Date Uploaded</th>
          <th>Add to <%= t('datarepo.col_metaname') %>?</th>
        </tr>
      </thead>
      <tbody>
        <% @files.each do |file| %>
          <tr>
            <td><%= render_thumbnail_tag file, { class: "hidden-xs file_listing_thumbnail pull-left media-left" }, { suppress_link: true } %>
            <%= file.title_or_label %></td>
            <td class="text-center"><%= file.date_uploaded %></td>
            <td class="text-center"><%= check_box_tag 'batch_document_ids[]', file.id, @collection.member_ids.include?(file.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <hr />
  </div>
  <%= f.button("Add #{t('datarepo.gf_metaname').capitalize} to/remove from #{t('datarepo.col_metaname').capitalize}", class: 'btn btn-primary') %>
  <% end %>
<% end %>

app/views/collections/crossref_search.js.erb
$('#crossref_search_result').html("<%= j (render 'crossref_search_result') %>");
$('#crossref_search_result').slideDown("fast");
$('#add_related_url').show();

app/views/collections/datacite_search.js.erb
$('#new_form_area').hide();
$('#datacite_search_result').html("<%= j (render 'datacite_search_result') %>");
$('#datacite_search_result').slideDown("fast");

app/views/collections/datacite_search_error.js.erb
$('#datacite_search_result').html("<h2><%= j @datacite_error %></h2>");
$('#datacite_search_result').slideDown("fast");
$('#new_form_area').show();
$("#new_collection").trigger('reset');
$(".collection_creator ul li:gt(0)").remove();
$('input[type=text][readonly]').removeAttr('readonly');
$("#new_collection span").show();
$('input[type="checkbox"][name="request_doi"]').hide();
$('label[for="request_doi"]').hide();

app/views/collections/import_metadata.js.erb
$("#new_collection").trigger('reset');
var key_res_arr = <%= raw @result %>;
var title_array = key_res_arr["title"];
$("#collection_title").val(title_array[0]);
$("#collection_title").attr("readonly", "readonly");
var creator_array = key_res_arr["creator"];
$(".collection_creator ul li:nth-child(1) input").val(creator_array[0]);
$(".collection_creator ul li:nth-child(1) input").attr("readonly", "readonly");
$(".collection_creator ul li:nth-child(1) span").hide();
for (var i = 1; i < creator_array.length; i++) {
  $(".collection_creator ul").append('<li class="field-wrapper input-group input-append">' 
    + '<input  class="string multi_value optional form-control collection_creator form-control multi-text-field" name="collection[creator][]" value="'
    + creator_array[i] + '" id="collection_creator" '
    + 'aria-labelledby="collection_creator_label" type="text" readonly="readonly"/></li>');    
}
$(".collection_date_created ul li:nth-child(1) input").val(key_res_arr["publicationYear"]);
$(".collection_date_created ul li:nth-child(1) input").attr("readonly", "readonly");
$(".collection_date_created ul li:nth-child(1) span").hide();
$(".collection_publisher ul li:nth-child(1) input").val(key_res_arr["publisher"]);
$(".collection_publisher ul li:nth-child(1) input").attr("readonly", "readonly");
$(".collection_publisher ul li:nth-child(1) span").hide();
$(".collection_identifier ul li:nth-child(1) input").val(key_res_arr["doi"]);
$(".collection_identifier ul li:nth-child(1) input").attr("readonly", "readonly");
$(".collection_identifier ul li:nth-child(1) span").hide();
$('#datacite_search_result').hide();
$('#new_form_area').show();
$('input[type="checkbox"][name="request_doi"]').hide();
$('label[for="request_doi"]').hide();

app/views/collections/show.html.erb
<% @page_title = "#{@collection.title} - #{application_name}" %>

<%= render_breadcrumbs builder: Sufia::BootstrapBreadcrumbsBuilder %>
<%= render partial: 'dashboard/_index_partials/heading_actions.html.erb' %>
  <div itemscope itemtype="http://schema.org/CollectionPage" class="row">
    <div class="col-sm-2">
      <%= render partial: 'collections/media_display', locals: { generic_file: @collection } %>
      <% unless has_collection_search_parameters? %>
      <%= render partial: 'collections/show_actions' %>
      <% end %>
    </div>
    <div class="col-sm-10">
      <header>
        <h1><%= @presenter.title %></h1>
        <p class="collection_description"><%= @presenter.description %></p>
      </header>
      <% unless has_collection_search_parameters? %>
      <%= render 'collections/show_descriptions' %>
      <% end %>
    </div>
  </div>

<%= render 'sort_and_per_page' %>

<% if has_collection_search_parameters? %>
    <% header_title = "Search Results within this Dataset" %>
<% else %>
    <% header_title = "Items in this Dataset" %>
<% end %>

<div>
  <!-- Use CSS class h2 rather than HTML h2 tag to allow header and search box to align vertically -->
  <span class="h2"><%= header_title %></span>
  <%= render partial: 'search_form'%>
</div>

<%= render_document_index @member_docs %>

<%= render partial: 'paginate' %>